version: "3.9"
services:
  gmail:
    image: orchestranexus/gmail-mcp:v0.0.0
    command: bash -c "cd /root/.gmail-mcp/  && node /Gmail-MCP-Server-main/dist/index.js auth http://localhost:3000/oauth2callback & /scripts/start_bridge.sh"
    privileged: true
    tty: true
    network_mode: host
    volumes:
      - ../../scripts:/scripts
      - ../../scripts/gmail_auth.py:/root/gmail_auth.py
      - ./config:/config
      - ./auth/gcp-oauth.keys.json:/root/.gmail-mcp/gcp-oauth.keys.json
    environment:
      MCP_BRIDGE__CONFIG__FILE: /config/bridge_config.json

